version: '3.8'

services:
  db:
    image: postgres
    container_name: meu-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mouthBD
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mouth1234
